Repository CS3219-AY2324S1/ay2324s1-course-assessment-g28, pull requests merged in 2023-10, with the labels that each got.

#29 Frontend + Pairing Service Integration
  .deployment/local-docker/compose.yaml
  .gitignore
  backend/services/pairing/pairing-front/README.md
  backend/services/pairing/pairing-front/index.ts
  backend/services/pairing/pairing-front/test-client.js
  frontend/api/pairing/index.ts
  frontend/api/pairing/types.ts
  frontend/components/MatchingUI/MatchContext.tsx
  frontend/routes.ts
Labels: must have

#36 Pairing enhance
  backend/services/pairing/README.md
  backend/services/pairing/pairing-back/index.ts
  backend/services/pairing/pairing-back/src/channel-callbacks/pairing-request.ts
  backend/services/pairing/pairing-back/src/controllers/user-pairing.ts
  backend/services/pairing/pairing-back/src/models/match.ts
  backend/services/pairing/pairing-back/src/models/question.ts
  backend/services/pairing/pairing-back/src/models/user.ts
  backend/services/pairing/pairing-back/src/services/question/pp-question-service.ts
  backend/services/pairing/pairing-back/src/services/question/service.ts
  backend/services/pairing/pairing-back/src/utils/config.ts
  backend/services/pairing/pairing-back/test-client.js
  backend/services/pairing/pairing-back/test-client.ts
  backend/services/pairing/pairing-front/index.ts
  backend/services/pairing/pairing-front/test-client.js
Labels: bug, must have

#40 Add favorite language and option to edit it
  frontend/components/UserCreationCard/UserCreationForm/index.tsx
  frontend/components/UserCreationCard/index.tsx
  frontend/components/UserInfoCard/index.tsx
  frontend/components/UserProfileCard/AttemptsHeatMap/index.tsx
  frontend/components/UserProfileCard/UserInfo/DeleteUserButton/index.tsx
  frontend/components/UserProfileCard/UserInfo/EditUserButton/index.tsx
  frontend/components/UserProfileCard/UserInfo/index.tsx
  frontend/components/UserProfileCard/index.tsx
Labels: bug

#49 Implement Collaboration with Operational Transform
  backend/services/collab/package-lock.json
  backend/services/collab/package.json
  backend/services/collab/src/index.ts
  backend/services/collab/src/services/executionService.ts
  backend/services/collab/src/services/otService.ts
  backend/services/collab/src/services/wsService.ts
  frontend/components/Editor/CodeWindow/index.tsx
  frontend/components/Editor/MessageWindow/index.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: must have

#48 fix navbar and screen height issues (#44)
  frontend/components/Layout/index.tsx
  frontend/pages/_app.tsx
Labels: bug

#42 GCP-GKE Deployment
  .deployment/gcp-gke/cloudbuild.yaml
  .deployment/gcp-gke/k8-templates/frontend.yaml
  .deployment/gcp-gke/k8s-templates/peerprep-frontend.yaml
  .deployment/gcp-gke/k8s-templates/peerprep-pairing.yaml
  .deployment/gcp-gke/k8s-templates/peerprep-question.yaml
  .deployment/gcp-gke/k8s-templates/peerprep-user.yaml
  .deployment/local-docker/compose.yaml
  .deployment/local-k8s/README.md
  .deployment/local-k8s/build.sh
  .deployment/local-k8s/compose.yaml
  .deployment/local-k8s/k8s-templates/peerprep-frontend.yaml
  .deployment/local-k8s/k8s-templates/peerprep-pairing.yaml
  .deployment/local-k8s/k8s-templates/peerprep-question.yaml
  .deployment/local-k8s/k8s-templates/peerprep-user.yaml
  .deployment/local-k8s/k8s.yaml
  .deployment/local-k8s/start.sh
  backend/services/pairing/pairing-back/src/services/question/pp-question-service.ts
  backend/services/pairing/pairing-front/test-client.js
  backend/services/question/Dockerfile
  backend/services/question/package-lock.json
  backend/services/question/package.json
  backend/services/question/yarn.lock
  backend/services/user/.env.example
  backend/services/user/Dockerfile
  backend/services/user/package-lock.json
  backend/services/user/package.json
  backend/services/user/src/controller.ts
Labels: nice to have

#50 add dark and light mode #45
  frontend/api/questions/constants.ts
  frontend/components/Button/index.tsx
  frontend/components/Card/index.tsx
  frontend/components/ComplexityChip/index.tsx
  frontend/components/Layout/index.tsx
  frontend/components/MatchingUI/cards/SelectDifficultyCard.tsx
  frontend/components/Navbar/ThemeSwitcher.tsx
  frontend/components/Navbar/UserDropdown.tsx
  frontend/components/Navbar/brand.tsx
  frontend/components/Navbar/index.tsx
  frontend/components/QuestionCreationForm/CategoryAdder.tsx
  frontend/components/QuestionCreationForm/index.tsx
  frontend/components/QuestionDescription/index.tsx
  frontend/components/QuestionsCard/QuestionsTable/DeleteButton.tsx
  frontend/components/QuestionsCard/QuestionsTable/TableSelectors.tsx
  frontend/components/QuestionsCard/QuestionsTable/index.tsx
  frontend/components/UserProfileCard/AttemptsHeatMap/index.tsx
  frontend/components/UserProfileCard/RecentAttempts/index.tsx
  frontend/components/UserProfileCard/UserInfo/DeleteUserButton/index.tsx
  frontend/components/UserProfileCard/UserInfo/EditUserButton/index.tsx
  frontend/components/UserProfileCard/UserInfo/index.tsx
  frontend/middleware.ts
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/pages/login/index.tsx
  frontend/routes.ts
  frontend/styles/globals.css
  frontend/tailwind.config.ts
  frontend/yarn.lock
Labels: enhancement, nice to have
